language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
        artifacts: true
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
        artifacts: true
      env: COMPILER=g++-5

before_install:
  - sudo apt-get update -qq
  - if [ "$COMPILER" = "g++-4.9" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$COMPILER" = "g++-4.9" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$COMPILER" = "g++-5" ]; then sudo apt-get install -qq g++-5; fi
  - if [ "$COMPILER" = "g++-5" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y gperf
  - sudo apt-get install -y libevent-dev
  - sudo apt-get install -y uuid-dev
  - sudo apt-get install -y python-sphinx
  - sudo apt-get install -y libhiredis-dev

script:
  - ./bootstrap.sh -a
  - ./configure
  - make
  - make test
