# Use new trusty images, should yield newer compilers and packages
sudo: required
# dist: precise
language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y gperf
  - sudo apt-get install -y libevent-dev
  - sudo apt-get install -y uuid-dev
  - sudo apt-get install -y python-sphinx

script:
  - ./bootstrap.sh -a
  - ./configure
  - make
  - make test
