/*  vim:expandtab:shiftwidth=2:tabstop=2:smarttab:
 *
 *  Gearmand client and server library.
 *
 *  Copyright (C) 2026 Data Differential, http://datadifferential.com/
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are
 *  met:
 *
 *      * Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *
 *      * Redistributions in binary form must reproduce the above
 *  copyright notice, this list of conditions and the following disclaimer
 *  in the documentation and/or other materials provided with the
 *  distribution.
 *
 *      * The names of its contributors may not be used to endorse or
 *  promote products derived from this software without specific prior
 *  written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 * @file
 *
 * Explicit SSL connectivity test for #56: unlike tests/protocol.cc, which
 * only exercises SSL when the test binary happens to be invoked with
 * --ssl (which "make check" never does), this binary always requests SSL,
 * so it gives an unambiguous SKIP/PASS/FAIL signal for SSL connectivity
 * instead of silently never being exercised.
 *
 * The cert/key pair it connects with is generated by the build (see
 * libtest/include.am) into the absolute path baked into libtest/ssl.h --
 * it has to be an absolute path because main() chdir()s into a scratch
 * temp directory before any test's world_create() runs.
 */

#include "gear_config.h"
#include <libtest/test.hpp>

using namespace libtest;

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <sys/stat.h>

#define GEARMAN_CORE
#include "libgearman/common.h"
#include "libgearman/packet.hpp"

#include "libgearman/universal.hpp"
#include "libgearman/protocol/echo.h"

#ifndef __INTEL_COMPILER
#pragma GCC diagnostic ignored "-Wold-style-cast"
#endif

static void error_logger(const char* message, gearman_verbose_t, void*)
{
  Error << message;
}

#if defined(HAVE_SSL) && HAVE_SSL
static bool file_is_non_empty(const char *path)
{
  struct stat st;
  return (stat(path, &st) == 0 and st.st_size > 0);
}
#endif // defined(HAVE_SSL) && HAVE_SSL

static test_return_t SSL_ECHO_TEST(void *)
{
  vchar_t data;
  vchar::make(data, 2048);

  gearman_universal_st universal;
  gearman_set_log_fn(universal, error_logger, NULL, GEARMAN_VERBOSE_ERROR);
  universal.ssl(true);

  gearman_packet_st message;
  gearman_string_t workload= { vchar_param(data) };

  ASSERT_EQ(GEARMAN_SUCCESS, libgearman::protocol::echo(universal, message, workload));

  gearman_connection_st *connection;
  ASSERT_TRUE(connection= gearman_connection_create(universal, GEARMAN_DEFAULT_TCP_HOST, libtest::default_port()));

  ASSERT_EQ(GEARMAN_SUCCESS, connection->send_packet(message, true));

  size_t length;
  gearman_return_t ret;
  gearman_packet_st recv_message;
  ASSERT_TRUE(connection->receiving(recv_message, ret, true));
  ASSERT_EQ(GEARMAN_SUCCESS, ret);
  ASSERT_TRUE(recv_message.value(length));
  ASSERT_EQ(length, data.size());

  delete connection;
  gearman_packet_free(&recv_message);
  gearman_packet_free(&message);
  gearman_universal_free(universal);

  return TEST_SUCCESS;
}

#if defined(HAVE_SSL) && HAVE_SSL
// Regression test for #503: gearman_universal_st::ctx_ssl() used to call
// abort() on any recoverable SSL init failure (bad/unreadable CA, cert, or
// key file), crashing the whole process instead of returning an error the
// caller could handle. If that regresses, this test process itself
// crashes with SIGABRT rather than reporting a clean FAIL.
static test_return_t SSL_BAD_CERT_NO_ABORT_TEST(void *)
{
  gearman_universal_st universal;
  gearman_set_log_fn(universal, error_logger, NULL, GEARMAN_VERBOSE_ERROR);
  universal.ssl(true);
  universal.ssl_ca_file("/no/such/gearman-test-ca.pem");
  universal.ssl_certificate("/no/such/gearman-test-cert.pem");
  universal.ssl_key("/no/such/gearman-test-key.pem");

  ASSERT_TRUE(universal.ctx_ssl() == NULL);
  ASSERT_EQ(GEARMAN_INVALID_ARGUMENT, universal.error_code());

  gearman_universal_free(universal);

  return TEST_SUCCESS;
}
#endif // defined(HAVE_SSL) && HAVE_SSL

test_st SSL_TESTS[] ={
  {"SSL echo request/response round-trip over TLS", 0, SSL_ECHO_TEST },
#if defined(HAVE_SSL) && HAVE_SSL
  {"ctx_ssl() returns error instead of abort() on bad cert/key path (#503)", 0, SSL_BAD_CERT_NO_ABORT_TEST },
#endif
  {0, 0, 0}
};

collection_st collection[] ={
  {"ssl", 0, 0, SSL_TESTS},
  {0, 0, 0, 0}
};

static void *world_create(server_startup_st& servers, test_return_t& rc)
{
  rc= TEST_SUCCESS;

#if !defined(HAVE_SSL) || !HAVE_SSL
  (void)servers;
  rc= TEST_SKIPPED;
  return NULL;
#else
  // Cert generation needs the "openssl" CLI tool (see libtest/include.am);
  // if it wasn't available at build time, the build leaves empty
  // placeholder files here instead of failing the whole build.
  if (file_is_non_empty(YATL_CERT_PEM) == false or file_is_non_empty(YATL_CERT_KEY_PEM) == false)
  {
    rc= TEST_SKIPPED;
    return NULL;
  }

  libtest::is_ssl(true);

  SKIP_UNLESS(server_startup(servers, "gearmand", libtest::default_port(), NULL));

  return NULL;
#endif
}

void get_world(libtest::Framework *world)
{
  world->collections(collection);
  world->create(world_create);
}
