name: GitHub Actions CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: ${{ matrix.config.os }} ${{ matrix.config.cc }}-${{ matrix.config.tag }}

    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.container }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {name: 'ubuntu-16.04 gcc-4.8', os: ubuntu-latest, container: 'ubuntu:16.04', cc: 'gcc', cxx: 'g++', tag: '4.8'}
          - {name: 'ubuntu-16.04 gcc-4.9', os: ubuntu-latest, container: 'ubuntu:16.04', cc: 'gcc', cxx: 'g++', tag: '4.9'}
          - {os: ubuntu-18.04, cc: 'gcc', cxx: 'g++', tag: '5'}
          - {os: ubuntu-18.04, cc: 'gcc', cxx: 'g++', tag: '6'}
          - {os: ubuntu-18.04, cc: 'gcc', cxx: 'g++', tag: '7'}
          - {os: ubuntu-18.04, cc: 'gcc', cxx: 'g++', tag: '8'}
          - {os: ubuntu-20.04, cc: 'gcc', cxx: 'g++', tag: '9'}
          - {os: ubuntu-20.04, cc: 'gcc', cxx: 'g++', tag: '10'}

    env:
      CC: ${{ matrix.config.cc }}-${{ matrix.config.tag }}
      CXX: ${{ matrix.config.cxx }}-${{ matrix.config.tag }}

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install -y libboost-all-dev gperf libevent-dev uuid-dev sphinx-doc sphinx-common libhiredis-dev ${{ matrix.config.cc }}-${{ matrix.config.tag }} ${{ matrix.config.cxx }}-${{ matrix.config.tag }}
    - name: bootstrap
      run: ./bootstrap.sh -a
    - name: configure
      run: ./configure --enable-ssl
    - name: make
      run: ${CC} --version && make
    - name: make test
      run: ${CC} --version && make test
